### ISSUE TITLE
A right bracket in a folder name causes an error when watching files

### ISSUE THREAD

**Issue by qdirks** [gulpjs/glob-watcher#78]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [ ] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
I expected the normal file watching behavior of triggering a callback when a change occurs to a watched file.

### What actually happened?
After running the gulp command, I received an error in the terminal stating 'Error: no parsers registered for: "]"'.

### Please give us a sample of your gulpfile

```js
const gulp = require('gulp');

function change(cb) {
    console.log("A change occurred ");
    cb();
}

exports.default = function watch() {
    gulp.watch(['./**/*.js', '!./node_modules/'], change);
};
```

### Terminal output / screenshots

```sh
H:\projects\browser-projects\gulp-test-bug>gulp
[19:27:35] Using gulpfile H:\projects\browser-projects\gulp-test-bug\gulpfile.js
[19:27:35] Starting 'default'...
[19:27:35] 'default' errored after 31 ms
[19:27:35] Error: no parsers registered for: "]"
    at parse (H:\projects\browser-projects\gulp-test-bug\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (H:\projects\browser-projects\gulp-test-bug\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (H:\projects\browser-projects\gulp-test-bug\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (H:\projects\browser-projects\gulp-test-bug\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (H:\projects\browser-projects\gulp-test-bug\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (H:\projects\browser-projects\gulp-test-bug\node_modules\braces\lib\braces.js:87:18)
    at create (H:\projects\browser-projects\gulp-test-bug\node_modules\braces\index.js:142:15)
    at memoize (H:\projects\browser-projects\gulp-test-bug\node_modules\braces\index.js:298:13)
    at Function.braces.create (H:\projects\browser-projects\gulp-test-bug\node_modules\braces\index.js:165:10)
    at Function.braces.expand (H:\projects\browser-projects\gulp-test-bug\node_modules\braces\index.js:81:17)
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: Windows 11 version 22H2 build 22621.674
* node version (run `node -v`): 12.18.3
* npm version (run `npm -v`): 8.12.1
* gulp version (run `gulp -v`): cli 2.3.0 local 4.0.2

### Additional information

The folder's full name was `[001]`. This issue is fixed after forking and updating to the latest chokidar package which gets rid of the snapdragon dependency. After reading the other open and closed issues, I understand why gulpjs team has not already updated the dependency, however it is possible for individual users to fork and update themselves if this is an issue. Thanks :)

**Comment by phated** [comment]
Thanks for opening this to share a workaround for people looking. We'll be upgrading chokidar as part of #76 so I'm going to close this as a duplicate.
